<?php

namespace Kkdshka\TodoList\Model;

use \PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-15 at 19:13:06.
 */
class TaskTest extends TestCase {

    /**
     * @test
     * @covers Kkdshka\TodoList\Model\Task::complete
     */
    public function shouldCompleteTask() {
        $task = new Task('Test subject');
        $this->assertFalse($task->isCompleted());
        
        $task->complete();
        
        $this->assertTrue($task->isCompleted());
    }
}