<?php
declare (strict_types = 1);

namespace Kkdshka\TodoList\Model;

use \PHPUnit\Framework\TestCase;
use Phake;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-15 at 19:13:06.
 */
class TaskTest extends TestCase {

    private $task;
    
    public function setUp() {
        $user = Phake::mock(User::class);
        $this->task = new Task($user, 'Test subject');
    }
    
    /**
     * @test
     * @covers Kkdshka\TodoList\Model\Task::setId
     */
    public function shouldSetId() {
        $this->task->setId(1);
        
        $this->assertEquals(1, $this->task->getId());
    }
    
    /**
     * @test
     * @covers Kkdshka\TodoList\Model\Task::setId
     * @expectedException BadMethodCallException
     * @expectedExceptionMessage Id had been already set.
     */
    public function shouldNotAllowChangeId() {
        $this->task->setId(1);
        $this->task->setId(2);
    }
    
    /**
     * @test
     * @covers Kkdshka\TodoList\Model\Task::hasId
     */
    public function shouldDetermineIfTaskHasId() {
        $this->assertFalse($this->task->hasId());
        
        $this->task->setId(1);
        
        $this->assertTrue($this->task->hasId());
    }
    
    /**
     * @test
     * @covers Kkdshka\TodoList\Model\Task::setPriority
     * @expectedException InvalidArgumentException
     * @expectedExceptionMessage Invalid priority 7 given.
     */
    public function shouldNotAllowWrongPriority() {
        $this->task->setPriority(7);
    }
    
    /**
     * @test
     * @covers Kkdshka\TodoList\Model\Task::setStatus
     * @expectedException InvalidArgumentException
     * @expectedExceptionMessage Invalid status strange given.
     */
    public function shouldNotAllowWrongStatus() {
        $this->task->setStatus('strange');
    }
    
}
