<?php

namespace Kkdshka\TodoList\Repository;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-14 at 18:41:17.
 */
class RepositoryFactoryTest extends TestCase {
    
    private static $filename;
    
    private $factory;
    
    public function __construct($name = null, array $data = [], $dataName = '') {
        parent::__construct($name, $data, $dataName);
        self::$filename = tempnam(sys_get_temp_dir(), 'fct');
    }
    
    public function setUp() {
        file_put_contents(self::$filename, "");
        $this->factory = new RepositoryFactory;
    }
    
    public static function tearDownAfterClass() {
        unlink(self::$filename);
    }
    
    /**
     * @test
     * @dataProvider shouldCreateRepositoryProvider
     */
    public function shouldCreateRepository(string $connectionUrl, string $class) {
        $repository = $this->factory->create($connectionUrl);
        $this->assertInstanceOf($class, $repository);
        $repository->close();
    }
    
    public function shouldCreateRepositoryProvider() : array {
        return [
            ["csv:" . self::$filename, CsvRepository::class],
            ["sqlite:" . self::$filename, SqliteRepository::class]
        ];
    }

    /**
     * @test
     * @expectedException RuntimeException
     * @expectedExceptionMessage Unknown protocol unexisted
     * @covers Kkdshka\TodoList\Repository\RepositoryFactory::create
     */
    public function shouldNotCreateOtherRepository() {
        $this->factory->create("unexisted:" . self::$filename);
    }
}
